spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      # show_sql: true
        format_sql: true

# 페이징 관련 글로벌 설정: 스프링 부트
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
 #       one-indexed-parameters: true
# 1부터 인덱스 시작  그런데 이 방법은
#  web에서 page 파라미터를 -1 처리 할 뿐이다. 따라서 응답값인 Page 에 모두 0 페이지 인덱스를
#  사용하는 한계가 있다.
logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace #쿼리문에서 파라미터 값까지 확인가능!